server:
  port: 8092    
spring:     #定义springmvc视图解析器
  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp

dubbo:
  scan:
    basePackages: com.jt  #dubbo包扫描
  application:
    name: consumer-user #服务名称
  registry:
    address: zookeeper://192.168.96.133:2181?backup=192.168.96.133:2182,192.168.96.133:2183
  